### ISSUE TITLE
RENDEZVOUS=file:///tmp/vfl && WORLD_SIZE=3 && RANK=0 python train_multi.py

### ISSUE THREAD

**Issue by gogll2** [yuanbenio/crypten_vfl_demo#3]
你好，这个命令在windows下运行报错如下。
有办法在windows系统上运行吗？谢谢

(fedavg) F:\github\crypten_vfl_demo-main>RENDEZVOUS=file:///tmp/vfl && WORLD_SIZE=3 && RANK=0 python train_multi.py
'RENDEZVOUS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by purp1emood** [comment]
> 你好，这个命令在windows下运行报错如下。 有办法在windows系统上运行吗？谢谢
> 
> (fedavg) F:\github\crypten_vfl_demo-main>RENDEZVOUS=file:///tmp/vfl && WORLD_SIZE=3 && RANK=0 python train_multi.py 'RENDEZVOUS' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

请问这个问题是如何解决的呢
